### ISSUE TITLE
"Esc" key being reassigned when journal is opened

### ISSUE THREAD

**Issue by AyJayCoding** [christopheml/soulshape-journal#20]
When the soulshape journal is opened, the "Esc" key is reassigned to close the journal. If the journal is closed by clicking with the mouse on the close button (x in top right corner), the "Esc" key is not assigned back to the default (which is to trigger the game menu if not otherwise assigned). By reopening the journal and using "Esc" to close the journal, the normal functionality of the "Esc" key is returned. However it should be avoided reassigning the "Esc" key if at all possible when the journal is open.

**Comment by christopheml** [comment]
Hello, I'm on a trip abroad and will be investingating issues asap.
Thanks for the reporting.

AFAIK, addons use different ways of adding a new tab to the collection journal that may not be compatible, I'll see if I can find something that works properly. I don't remember adding specific behavior around the ESC key, but I'll need to check this.

**Comment by christopheml** [comment]
I dug a bit into the issue. First off thank you for the accuracy of your report, that's a lot of time saved on my part.
I'll need a bit more time to figure out what went wrong. Because of the non-standard way needed to display a window on top of the collections journal, there are some weird interactions I need to sort out and understand why escape key presses are 'eaten' when closing using the button.

**Comment by christopheml** [comment]
Bug found, was located in the SecureTabs lib I'm using to display tab. I'll patch the version I embed and I'll provide a fix to the library author.
