### ISSUE TITLE
I translated into Russian the addon Soulshape Journal

### ISSUE THREAD

**Issue by Hubbotu** [christopheml/soulshape-journal#6]
https://github.com/Hubbotu/Soulshape-Journal_RUS/blob/main/ruRU.lua

**Comment by christopheml** [comment]
Hello, thanks a lot for this contribution.

How would you like to be credited? As "Hobbotu" or another name?
Also keep in mind that the addon isn't completely final and some translations are susceptible to change in the coming days (especially soulshapes associated with the Spectral Feed item in Revendreth since the guide kinda sucks right now).

**Comment by Hubbotu** [comment]
Hi. Yes add as ZamestoTV. If the translation changes, write to me about it at curseforge.com

**Comment by christopheml** [comment]
Perfect, will do that. Thanks for your contribution!
